package com.flt.dao.client;

import com.flt.dao.model.AccessLog;
import com.flt.dao.model.AccessLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccessLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	int countByExample(AccessLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	int deleteByExample(AccessLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	int insert(AccessLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	int insertSelective(AccessLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	List<AccessLog> selectByExample(AccessLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	AccessLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	int updateByExampleSelective(@Param("record") AccessLog record,
			@Param("example") AccessLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	int updateByExample(@Param("record") AccessLog record,
			@Param("example") AccessLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	int updateByPrimaryKeySelective(AccessLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
	 * @mbggenerated  Thu Mar 06 09:56:06 CST 2014
	 */
	int updateByPrimaryKey(AccessLog record);
}