package com.flt.dao.client;

import com.flt.dao.model.Brand;
import com.flt.dao.model.BrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    int countByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    int deleteByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    List<Brand> selectByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    Brand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    int updateByExampleSelective(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    int updateByExample(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbggenerated Fri Jan 24 01:16:24 CST 2014
     */
    int updateByPrimaryKey(Brand record);
}