package com.flt.dao.client;

import com.flt.dao.model.Category;
import com.flt.dao.model.CategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	int countByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	int deleteByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	int deleteByPrimaryKey(Integer id_category);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	int insert(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	int insertSelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	List<Category> selectByExample(CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	Category selectByPrimaryKey(Integer id_category);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Category record,
			@Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	int updateByExample(@Param("record") Category record,
			@Param("example") CategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	int updateByPrimaryKeySelective(Category record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	int updateByPrimaryKey(Category record);
}