package com.flt.dao.client;

import com.flt.dao.model.Example;
import com.flt.dao.model.ExampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_example
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    int countByExample(ExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_example
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    int deleteByExample(ExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_example
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_example
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    int insert(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_example
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    int insertSelective(Example record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_example
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    List<Example> selectByExample(ExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_example
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") Example record, @Param("example") ExampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_example
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    int updateByExample(@Param("record") Example record, @Param("example") ExampleExample example);
}