package com.flt.dao.client;

import com.flt.dao.model.Passage;
import com.flt.dao.model.PassageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PassageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	int countByExample(PassageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	int deleteByExample(PassageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	int insert(Passage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	int insertSelective(Passage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	List<Passage> selectByExample(PassageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	Passage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Passage record,
			@Param("example") PassageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	int updateByExample(@Param("record") Passage record,
			@Param("example") PassageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	int updateByPrimaryKeySelective(Passage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table passage
	 * @mbggenerated  Sat Feb 01 21:15:19 CST 2014
	 */
	int updateByPrimaryKey(Passage record);
}