package com.flt.dao.client;

import com.flt.dao.model.PMenu;
import com.flt.dao.model.PMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	int countByExample(PMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	int deleteByExample(PMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	int deleteByPrimaryKey(Integer menu_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	int insert(PMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	int insertSelective(PMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	List<PMenu> selectByExample(PMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	PMenu selectByPrimaryKey(Integer menu_id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	int updateByExampleSelective(@Param("record") PMenu record,
			@Param("example") PMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	int updateByExample(@Param("record") PMenu record,
			@Param("example") PMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	int updateByPrimaryKeySelective(PMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	int updateByPrimaryKey(PMenu record);
}