package com.flt.dao.client;

import com.flt.dao.model.resource;
import com.flt.dao.model.resourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface resourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    int countByExample(resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    int deleteByExample(resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    int insert(resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    int insertSelective(resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    List<resource> selectByExample(resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    resource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    int updateByExampleSelective(@Param("record") resource record, @Param("example") resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    int updateByExample(@Param("record") resource record, @Param("example") resourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    int updateByPrimaryKeySelective(resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Thu Jan 16 13:36:19 CST 2014
     */
    int updateByPrimaryKey(resource record);
}