package com.flt.dao.model;

import java.util.Date;

public class Article {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.price
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.discount
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Double discount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.name
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.u_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Date uDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.c_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Date cDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.idx
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.menu_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.channel_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.brand_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.user_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.sale_count
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer saleCount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.id
	 * @return  the value of article.id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.id
	 * @param id  the value for article.id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.price
	 * @return  the value of article.price
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.price
	 * @param price  the value for article.price
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.discount
	 * @return  the value of article.discount
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Double getDiscount() {
		return discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.discount
	 * @param discount  the value for article.discount
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.name
	 * @return  the value of article.name
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.name
	 * @param name  the value for article.name
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.u_dt
	 * @return  the value of article.u_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Date getuDt() {
		return uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.u_dt
	 * @param uDt  the value for article.u_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setuDt(Date uDt) {
		this.uDt = uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.c_dt
	 * @return  the value of article.c_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Date getcDt() {
		return cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.c_dt
	 * @param cDt  the value for article.c_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setcDt(Date cDt) {
		this.cDt = cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.idx
	 * @return  the value of article.idx
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.idx
	 * @param idx  the value for article.idx
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.menu_id
	 * @return  the value of article.menu_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.menu_id
	 * @param menuId  the value for article.menu_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.channel_id
	 * @return  the value of article.channel_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.channel_id
	 * @param channelId  the value for article.channel_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setChannelId(Integer channelId) {
		this.channelId = channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.brand_id
	 * @return  the value of article.brand_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.brand_id
	 * @param brandId  the value for article.brand_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.user_id
	 * @return  the value of article.user_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.user_id
	 * @param userId  the value for article.user_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.sale_count
	 * @return  the value of article.sale_count
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getSaleCount() {
		return saleCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.sale_count
	 * @param saleCount  the value for article.sale_count
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setSaleCount(Integer saleCount) {
		this.saleCount = saleCount;
	}
}