package com.flt.dao.model;

import java.util.Date;

public class Ball {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.id
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.term
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Integer term;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.make_date_time
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Date makeDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.day
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.red_one
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Integer redOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.red_two
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Integer redTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.red_three
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Integer redThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.red_four
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Integer redFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.red_five
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Integer redFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.red_six
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Integer redSix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ball.blue
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    private Integer blue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.id
     *
     * @return the value of ball.id
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.id
     *
     * @param id the value for ball.id
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.term
     *
     * @return the value of ball.term
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Integer getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.term
     *
     * @param term the value for ball.term
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setTerm(Integer term) {
        this.term = term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.make_date_time
     *
     * @return the value of ball.make_date_time
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Date getMakeDateTime() {
        return makeDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.make_date_time
     *
     * @param makeDateTime the value for ball.make_date_time
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setMakeDateTime(Date makeDateTime) {
        this.makeDateTime = makeDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.day
     *
     * @return the value of ball.day
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.day
     *
     * @param day the value for ball.day
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setDay(String day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.red_one
     *
     * @return the value of ball.red_one
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Integer getRedOne() {
        return redOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.red_one
     *
     * @param redOne the value for ball.red_one
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setRedOne(Integer redOne) {
        this.redOne = redOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.red_two
     *
     * @return the value of ball.red_two
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Integer getRedTwo() {
        return redTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.red_two
     *
     * @param redTwo the value for ball.red_two
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setRedTwo(Integer redTwo) {
        this.redTwo = redTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.red_three
     *
     * @return the value of ball.red_three
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Integer getRedThree() {
        return redThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.red_three
     *
     * @param redThree the value for ball.red_three
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setRedThree(Integer redThree) {
        this.redThree = redThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.red_four
     *
     * @return the value of ball.red_four
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Integer getRedFour() {
        return redFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.red_four
     *
     * @param redFour the value for ball.red_four
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setRedFour(Integer redFour) {
        this.redFour = redFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.red_five
     *
     * @return the value of ball.red_five
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Integer getRedFive() {
        return redFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.red_five
     *
     * @param redFive the value for ball.red_five
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setRedFive(Integer redFive) {
        this.redFive = redFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.red_six
     *
     * @return the value of ball.red_six
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Integer getRedSix() {
        return redSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.red_six
     *
     * @param redSix the value for ball.red_six
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setRedSix(Integer redSix) {
        this.redSix = redSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ball.blue
     *
     * @return the value of ball.blue
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public Integer getBlue() {
        return blue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ball.blue
     *
     * @param blue the value for ball.blue
     *
     * @mbggenerated Wed Jan 15 13:34:49 CST 2014
     */
    public void setBlue(Integer blue) {
        this.blue = blue;
    }
}