package com.flt.dao.model;

import java.util.Date;

public class Brand {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brand.id
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brand.name
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brand.thumbnail
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	private String thumbnail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brand.type
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brand.u_dt
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	private Date uDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brand.c_dt
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	private Date cDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brand.idx
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column brand.user_id
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brand.id
	 * @return  the value of brand.id
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brand.id
	 * @param id  the value for brand.id
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brand.name
	 * @return  the value of brand.name
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brand.name
	 * @param name  the value for brand.name
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brand.thumbnail
	 * @return  the value of brand.thumbnail
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public String getThumbnail() {
		return thumbnail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brand.thumbnail
	 * @param thumbnail  the value for brand.thumbnail
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brand.type
	 * @return  the value of brand.type
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brand.type
	 * @param type  the value for brand.type
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brand.u_dt
	 * @return  the value of brand.u_dt
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public Date getuDt() {
		return uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brand.u_dt
	 * @param uDt  the value for brand.u_dt
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public void setuDt(Date uDt) {
		this.uDt = uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brand.c_dt
	 * @return  the value of brand.c_dt
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public Date getcDt() {
		return cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brand.c_dt
	 * @param cDt  the value for brand.c_dt
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public void setcDt(Date cDt) {
		this.cDt = cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brand.idx
	 * @return  the value of brand.idx
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brand.idx
	 * @param idx  the value for brand.idx
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column brand.user_id
	 * @return  the value of brand.user_id
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column brand.user_id
	 * @param userId  the value for brand.user_id
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}