package com.flt.dao.model;

import java.util.Date;

public class Menu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.id
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.name
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.p_id
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	private Integer pId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.u_dt
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	private Date uDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.c_dt
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	private Date cDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu.idx
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	private Integer idx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.id
	 * @return  the value of menu.id
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.id
	 * @param id  the value for menu.id
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.name
	 * @return  the value of menu.name
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.name
	 * @param name  the value for menu.name
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.p_id
	 * @return  the value of menu.p_id
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public Integer getpId() {
		return pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.p_id
	 * @param pId  the value for menu.p_id
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public void setpId(Integer pId) {
		this.pId = pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.u_dt
	 * @return  the value of menu.u_dt
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public Date getuDt() {
		return uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.u_dt
	 * @param uDt  the value for menu.u_dt
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public void setuDt(Date uDt) {
		this.uDt = uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.c_dt
	 * @return  the value of menu.c_dt
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public Date getcDt() {
		return cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.c_dt
	 * @param cDt  the value for menu.c_dt
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public void setcDt(Date cDt) {
		this.cDt = cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu.idx
	 * @return  the value of menu.idx
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu.idx
	 * @param idx  the value for menu.idx
	 * @mbggenerated  Wed Jan 08 15:35:10 CST 2014
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}
}