package com.flt.dao.model;

import java.util.Date;

public class Passage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column passage.id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column passage.text
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private String text;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column passage.type
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column passage.num
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column passage.idx
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column passage.u_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Date uDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column passage.c_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Date cDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column passage.user_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column passage.id
	 * @return  the value of passage.id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column passage.id
	 * @param id  the value for passage.id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column passage.text
	 * @return  the value of passage.text
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column passage.text
	 * @param text  the value for passage.text
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column passage.type
	 * @return  the value of passage.type
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column passage.type
	 * @param type  the value for passage.type
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column passage.num
	 * @return  the value of passage.num
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column passage.num
	 * @param num  the value for passage.num
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column passage.idx
	 * @return  the value of passage.idx
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column passage.idx
	 * @param idx  the value for passage.idx
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column passage.u_dt
	 * @return  the value of passage.u_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Date getuDt() {
		return uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column passage.u_dt
	 * @param uDt  the value for passage.u_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setuDt(Date uDt) {
		this.uDt = uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column passage.c_dt
	 * @return  the value of passage.c_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Date getcDt() {
		return cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column passage.c_dt
	 * @param cDt  the value for passage.c_dt
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setcDt(Date cDt) {
		this.cDt = cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column passage.user_id
	 * @return  the value of passage.user_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column passage.user_id
	 * @param userId  the value for passage.user_id
	 * @mbggenerated  Thu Jan 30 00:55:21 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}