package com.flt.dao.client;

import com.flt.dao.model.Comment;
import com.flt.dao.model.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	int countByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	int deleteByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	List<Comment> selectByExample(CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	Comment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Comment record,
			@Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	int updateByExample(@Param("record") Comment record,
			@Param("example") CommentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Fri Jan 31 14:52:06 CST 2014
	 */
	int updateByPrimaryKey(Comment record);
}