package com.flt.dao.client;

import com.flt.dao.model.Consume;
import com.flt.dao.model.ConsumeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsumeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	int countByExample(ConsumeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	int deleteByExample(ConsumeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	int insert(Consume record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	int insertSelective(Consume record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	List<Consume> selectByExample(ConsumeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	Consume selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Consume record,
			@Param("example") ConsumeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	int updateByExample(@Param("record") Consume record,
			@Param("example") ConsumeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	int updateByPrimaryKeySelective(Consume record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table consumer
	 * @mbggenerated  Sat Jan 25 13:20:38 CST 2014
	 */
	int updateByPrimaryKey(Consume record);
}