package com.flt.dao.client;

import com.flt.dao.model.Order;
import com.flt.dao.model.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	int countByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	int deleteByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	List<Order> selectByExample(OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	Order selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Order record,
			@Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	int updateByExample(@Param("record") Order record,
			@Param("example") OrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	int updateByPrimaryKeySelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_order
	 * @mbggenerated  Fri Jan 31 14:52:07 CST 2014
	 */
	int updateByPrimaryKey(Order record);
}