package com.flt.dao.client;

import com.flt.dao.model.Resource;
import com.flt.dao.model.ResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	int countByExample(ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	int deleteByExample(ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	int insert(Resource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	int insertSelective(Resource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	List<Resource> selectByExample(ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	Resource selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Resource record,
			@Param("example") ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	int updateByExample(@Param("record") Resource record,
			@Param("example") ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	int updateByPrimaryKeySelective(Resource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbggenerated  Mon Feb 03 17:00:19 CST 2014
	 */
	int updateByPrimaryKey(Resource record);
}