package com.flt.dao.model;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.id
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.login_id
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	private String loginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.password
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.name
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.id
	 * @return  the value of admin.id
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.id
	 * @param id  the value for admin.id
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.login_id
	 * @return  the value of admin.login_id
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	public String getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.login_id
	 * @param loginId  the value for admin.login_id
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.password
	 * @return  the value of admin.password
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.password
	 * @param password  the value for admin.password
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.name
	 * @return  the value of admin.name
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.name
	 * @param name  the value for admin.name
	 * @mbggenerated  Tue Jan 07 14:04:01 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}
}