package com.flt.dao.model;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.account_id
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.account_name
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.account_id
     *
     * @return the value of admin.account_id
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.account_id
     *
     * @param accountId the value for admin.account_id
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.account_name
     *
     * @return the value of admin.account_name
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.account_name
     *
     * @param accountName the value for admin.account_name
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbggenerated Thu Dec 26 15:44:13 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }
}