package com.flt.dao.model;

public class ArticleImg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_img.id
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_img.title
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_img.path
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_img.article_id
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	private Integer articleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_img.id
	 * @return  the value of article_img.id
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_img.id
	 * @param id  the value for article_img.id
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_img.title
	 * @return  the value of article_img.title
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_img.title
	 * @param title  the value for article_img.title
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_img.path
	 * @return  the value of article_img.path
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_img.path
	 * @param path  the value for article_img.path
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_img.article_id
	 * @return  the value of article_img.article_id
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	public Integer getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_img.article_id
	 * @param articleId  the value for article_img.article_id
	 * @mbggenerated  Tue Feb 18 14:27:14 CST 2014
	 */
	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}
}