package com.flt.dao.model;

import java.util.Date;

public class ArticleProperty {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_property.id
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_property.name
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_property.value
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_property.u_dt
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	private Date uDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_property.c_dt
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	private Date cDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_property.idx
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_property.article_id
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	private Integer articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_property.type
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	private String type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_property.id
	 * @return  the value of article_property.id
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_property.id
	 * @param id  the value for article_property.id
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_property.name
	 * @return  the value of article_property.name
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_property.name
	 * @param name  the value for article_property.name
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_property.value
	 * @return  the value of article_property.value
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_property.value
	 * @param value  the value for article_property.value
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_property.u_dt
	 * @return  the value of article_property.u_dt
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public Date getuDt() {
		return uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_property.u_dt
	 * @param uDt  the value for article_property.u_dt
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public void setuDt(Date uDt) {
		this.uDt = uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_property.c_dt
	 * @return  the value of article_property.c_dt
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public Date getcDt() {
		return cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_property.c_dt
	 * @param cDt  the value for article_property.c_dt
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public void setcDt(Date cDt) {
		this.cDt = cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_property.idx
	 * @return  the value of article_property.idx
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_property.idx
	 * @param idx  the value for article_property.idx
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_property.article_id
	 * @return  the value of article_property.article_id
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public Integer getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_property.article_id
	 * @param articleId  the value for article_property.article_id
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_property.type
	 * @return  the value of article_property.type
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_property.type
	 * @param type  the value for article_property.type
	 * @mbggenerated  Sun Jan 26 14:14:36 CST 2014
	 */
	public void setType(String type) {
		this.type = type;
	}
}