package com.flt.dao.model;

import java.util.Date;

public class Ball {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.id
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.term
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer term;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.make_date_time
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Date makeDateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.day
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private String day;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.red_one
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer redOne;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.red_two
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer redTwo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.red_three
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer redThree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.red_four
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer redFour;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.red_five
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer redFive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.red_six
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer redSix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.blue
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer blue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.summation_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer summationValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.median_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer medianValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.min_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer minValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.max_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Integer maxValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.variance_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Double varianceValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.e_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Double eValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ball.average_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	private Double averageValue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.id
	 * @return  the value of ball.id
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.id
	 * @param id  the value for ball.id
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.term
	 * @return  the value of ball.term
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getTerm() {
		return term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.term
	 * @param term  the value for ball.term
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setTerm(Integer term) {
		this.term = term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.make_date_time
	 * @return  the value of ball.make_date_time
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Date getMakeDateTime() {
		return makeDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.make_date_time
	 * @param makeDateTime  the value for ball.make_date_time
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setMakeDateTime(Date makeDateTime) {
		this.makeDateTime = makeDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.day
	 * @return  the value of ball.day
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public String getDay() {
		return day;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.day
	 * @param day  the value for ball.day
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setDay(String day) {
		this.day = day;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.red_one
	 * @return  the value of ball.red_one
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getRedOne() {
		return redOne;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.red_one
	 * @param redOne  the value for ball.red_one
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setRedOne(Integer redOne) {
		this.redOne = redOne;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.red_two
	 * @return  the value of ball.red_two
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getRedTwo() {
		return redTwo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.red_two
	 * @param redTwo  the value for ball.red_two
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setRedTwo(Integer redTwo) {
		this.redTwo = redTwo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.red_three
	 * @return  the value of ball.red_three
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getRedThree() {
		return redThree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.red_three
	 * @param redThree  the value for ball.red_three
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setRedThree(Integer redThree) {
		this.redThree = redThree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.red_four
	 * @return  the value of ball.red_four
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getRedFour() {
		return redFour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.red_four
	 * @param redFour  the value for ball.red_four
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setRedFour(Integer redFour) {
		this.redFour = redFour;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.red_five
	 * @return  the value of ball.red_five
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getRedFive() {
		return redFive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.red_five
	 * @param redFive  the value for ball.red_five
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setRedFive(Integer redFive) {
		this.redFive = redFive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.red_six
	 * @return  the value of ball.red_six
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getRedSix() {
		return redSix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.red_six
	 * @param redSix  the value for ball.red_six
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setRedSix(Integer redSix) {
		this.redSix = redSix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.blue
	 * @return  the value of ball.blue
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getBlue() {
		return blue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.blue
	 * @param blue  the value for ball.blue
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setBlue(Integer blue) {
		this.blue = blue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.summation_value
	 * @return  the value of ball.summation_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getSummationValue() {
		return summationValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.summation_value
	 * @param summationValue  the value for ball.summation_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setSummationValue(Integer summationValue) {
		this.summationValue = summationValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.median_value
	 * @return  the value of ball.median_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getMedianValue() {
		return medianValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.median_value
	 * @param medianValue  the value for ball.median_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setMedianValue(Integer medianValue) {
		this.medianValue = medianValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.min_value
	 * @return  the value of ball.min_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getMinValue() {
		return minValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.min_value
	 * @param minValue  the value for ball.min_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setMinValue(Integer minValue) {
		this.minValue = minValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.max_value
	 * @return  the value of ball.max_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Integer getMaxValue() {
		return maxValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.max_value
	 * @param maxValue  the value for ball.max_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setMaxValue(Integer maxValue) {
		this.maxValue = maxValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.variance_value
	 * @return  the value of ball.variance_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Double getVarianceValue() {
		return varianceValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.variance_value
	 * @param varianceValue  the value for ball.variance_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setVarianceValue(Double varianceValue) {
		this.varianceValue = varianceValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.e_value
	 * @return  the value of ball.e_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Double geteValue() {
		return eValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.e_value
	 * @param eValue  the value for ball.e_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void seteValue(Double eValue) {
		this.eValue = eValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ball.average_value
	 * @return  the value of ball.average_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public Double getAverageValue() {
		return averageValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ball.average_value
	 * @param averageValue  the value for ball.average_value
	 * @mbggenerated  Sat Jan 25 14:42:34 CST 2014
	 */
	public void setAverageValue(Double averageValue) {
		this.averageValue = averageValue;
	}
}