package com.flt.dao.model;

public class Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.id
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.name
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.img_bg
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    private String imgBg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.img_logo
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    private String imgLogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.phone
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.password
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_business.info
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.id
     *
     * @return the value of tb_business.id
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.id
     *
     * @param id the value for tb_business.id
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.name
     *
     * @return the value of tb_business.name
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.name
     *
     * @param name the value for tb_business.name
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.img_bg
     *
     * @return the value of tb_business.img_bg
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public String getImgBg() {
        return imgBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.img_bg
     *
     * @param imgBg the value for tb_business.img_bg
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public void setImgBg(String imgBg) {
        this.imgBg = imgBg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.img_logo
     *
     * @return the value of tb_business.img_logo
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public String getImgLogo() {
        return imgLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.img_logo
     *
     * @param imgLogo the value for tb_business.img_logo
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public void setImgLogo(String imgLogo) {
        this.imgLogo = imgLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.phone
     *
     * @return the value of tb_business.phone
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.phone
     *
     * @param phone the value for tb_business.phone
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.password
     *
     * @return the value of tb_business.password
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.password
     *
     * @param password the value for tb_business.password
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_business.info
     *
     * @return the value of tb_business.info
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_business.info
     *
     * @param info the value for tb_business.info
     *
     * @mbggenerated Sat Dec 05 11:14:55 CST 2015
     */
    public void setInfo(String info) {
        this.info = info;
    }
}