package com.flt.dao.model;

import java.util.ArrayList;
import java.util.List;

public class CategoryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public CategoryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andId_categoryIsNull() {
			addCriterion("id_category is null");
			return (Criteria) this;
		}

		public Criteria andId_categoryIsNotNull() {
			addCriterion("id_category is not null");
			return (Criteria) this;
		}

		public Criteria andId_categoryEqualTo(Integer value) {
			addCriterion("id_category =", value, "id_category");
			return (Criteria) this;
		}

		public Criteria andId_categoryNotEqualTo(Integer value) {
			addCriterion("id_category <>", value, "id_category");
			return (Criteria) this;
		}

		public Criteria andId_categoryGreaterThan(Integer value) {
			addCriterion("id_category >", value, "id_category");
			return (Criteria) this;
		}

		public Criteria andId_categoryGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_category >=", value, "id_category");
			return (Criteria) this;
		}

		public Criteria andId_categoryLessThan(Integer value) {
			addCriterion("id_category <", value, "id_category");
			return (Criteria) this;
		}

		public Criteria andId_categoryLessThanOrEqualTo(Integer value) {
			addCriterion("id_category <=", value, "id_category");
			return (Criteria) this;
		}

		public Criteria andId_categoryIn(List<Integer> values) {
			addCriterion("id_category in", values, "id_category");
			return (Criteria) this;
		}

		public Criteria andId_categoryNotIn(List<Integer> values) {
			addCriterion("id_category not in", values, "id_category");
			return (Criteria) this;
		}

		public Criteria andId_categoryBetween(Integer value1, Integer value2) {
			addCriterion("id_category between", value1, value2, "id_category");
			return (Criteria) this;
		}

		public Criteria andId_categoryNotBetween(Integer value1, Integer value2) {
			addCriterion("id_category not between", value1, value2,
					"id_category");
			return (Criteria) this;
		}

		public Criteria andCategoryNameIsNull() {
			addCriterion("category_name is null");
			return (Criteria) this;
		}

		public Criteria andCategoryNameIsNotNull() {
			addCriterion("category_name is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryNameEqualTo(String value) {
			addCriterion("category_name =", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotEqualTo(String value) {
			addCriterion("category_name <>", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameGreaterThan(String value) {
			addCriterion("category_name >", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameGreaterThanOrEqualTo(String value) {
			addCriterion("category_name >=", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameLessThan(String value) {
			addCriterion("category_name <", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameLessThanOrEqualTo(String value) {
			addCriterion("category_name <=", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameLike(String value) {
			addCriterion("category_name like", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotLike(String value) {
			addCriterion("category_name not like", value, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameIn(List<String> values) {
			addCriterion("category_name in", values, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotIn(List<String> values) {
			addCriterion("category_name not in", values, "categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameBetween(String value1, String value2) {
			addCriterion("category_name between", value1, value2,
					"categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryNameNotBetween(String value1, String value2) {
			addCriterion("category_name not between", value1, value2,
					"categoryName");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionIsNull() {
			addCriterion("category_description is null");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionIsNotNull() {
			addCriterion("category_description is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionEqualTo(String value) {
			addCriterion("category_description =", value, "categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionNotEqualTo(String value) {
			addCriterion("category_description <>", value,
					"categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionGreaterThan(String value) {
			addCriterion("category_description >", value, "categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("category_description >=", value,
					"categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionLessThan(String value) {
			addCriterion("category_description <", value, "categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionLessThanOrEqualTo(String value) {
			addCriterion("category_description <=", value,
					"categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionLike(String value) {
			addCriterion("category_description like", value,
					"categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionNotLike(String value) {
			addCriterion("category_description not like", value,
					"categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionIn(List<String> values) {
			addCriterion("category_description in", values,
					"categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionNotIn(List<String> values) {
			addCriterion("category_description not in", values,
					"categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionBetween(String value1,
				String value2) {
			addCriterion("category_description between", value1, value2,
					"categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryDescriptionNotBetween(String value1,
				String value2) {
			addCriterion("category_description not between", value1, value2,
					"categoryDescription");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeIsNull() {
			addCriterion("category_type is null");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeIsNotNull() {
			addCriterion("category_type is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeEqualTo(Integer value) {
			addCriterion("category_type =", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeNotEqualTo(Integer value) {
			addCriterion("category_type <>", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeGreaterThan(Integer value) {
			addCriterion("category_type >", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("category_type >=", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeLessThan(Integer value) {
			addCriterion("category_type <", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeLessThanOrEqualTo(Integer value) {
			addCriterion("category_type <=", value, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeIn(List<Integer> values) {
			addCriterion("category_type in", values, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeNotIn(List<Integer> values) {
			addCriterion("category_type not in", values, "categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeBetween(Integer value1, Integer value2) {
			addCriterion("category_type between", value1, value2,
					"categoryType");
			return (Criteria) this;
		}

		public Criteria andCategoryTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("category_type not between", value1, value2,
					"categoryType");
			return (Criteria) this;
		}

		public Criteria andIndIsNull() {
			addCriterion("ind is null");
			return (Criteria) this;
		}

		public Criteria andIndIsNotNull() {
			addCriterion("ind is not null");
			return (Criteria) this;
		}

		public Criteria andIndEqualTo(Integer value) {
			addCriterion("ind =", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndNotEqualTo(Integer value) {
			addCriterion("ind <>", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndGreaterThan(Integer value) {
			addCriterion("ind >", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndGreaterThanOrEqualTo(Integer value) {
			addCriterion("ind >=", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndLessThan(Integer value) {
			addCriterion("ind <", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndLessThanOrEqualTo(Integer value) {
			addCriterion("ind <=", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndIn(List<Integer> values) {
			addCriterion("ind in", values, "ind");
			return (Criteria) this;
		}

		public Criteria andIndNotIn(List<Integer> values) {
			addCriterion("ind not in", values, "ind");
			return (Criteria) this;
		}

		public Criteria andIndBetween(Integer value1, Integer value2) {
			addCriterion("ind between", value1, value2, "ind");
			return (Criteria) this;
		}

		public Criteria andIndNotBetween(Integer value1, Integer value2) {
			addCriterion("ind not between", value1, value2, "ind");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table p_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table p_category
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 31 17:10:26 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}