package com.flt.dao.model;

public class Category {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_category.id_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	private Integer id_category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_category.category_name
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	private String categoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_category.category_description
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	private String categoryDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_category.category_type
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	private Integer categoryType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_category.ind
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	private Integer ind;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_category.id_category
	 * @return  the value of p_category.id_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public Integer getId_category() {
		return id_category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_category.id_category
	 * @param id_category  the value for p_category.id_category
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public void setId_category(Integer id_category) {
		this.id_category = id_category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_category.category_name
	 * @return  the value of p_category.category_name
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_category.category_name
	 * @param categoryName  the value for p_category.category_name
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_category.category_description
	 * @return  the value of p_category.category_description
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public String getCategoryDescription() {
		return categoryDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_category.category_description
	 * @param categoryDescription  the value for p_category.category_description
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public void setCategoryDescription(String categoryDescription) {
		this.categoryDescription = categoryDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_category.category_type
	 * @return  the value of p_category.category_type
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public Integer getCategoryType() {
		return categoryType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_category.category_type
	 * @param categoryType  the value for p_category.category_type
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public void setCategoryType(Integer categoryType) {
		this.categoryType = categoryType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_category.ind
	 * @return  the value of p_category.ind
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public Integer getInd() {
		return ind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_category.ind
	 * @param ind  the value for p_category.ind
	 * @mbggenerated  Tue Dec 31 17:30:32 CST 2013
	 */
	public void setInd(Integer ind) {
		this.ind = ind;
	}
}