package com.flt.dao.model;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.id
     *
     * @mbggenerated Tue Jan 07 14:04:01 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.name
     *
     * @mbggenerated Tue Jan 07 14:04:01 CST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.id
     *
     * @return the value of channel.id
     *
     * @mbggenerated Tue Jan 07 14:04:01 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.id
     *
     * @param id the value for channel.id
     *
     * @mbggenerated Tue Jan 07 14:04:01 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.name
     *
     * @return the value of channel.name
     *
     * @mbggenerated Tue Jan 07 14:04:01 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.name
     *
     * @param name the value for channel.name
     *
     * @mbggenerated Tue Jan 07 14:04:01 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }
}