package com.flt.dao.model;

public class Channel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_channel.id
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_channel.name
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_channel.type
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_channel.ind
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    private Integer ind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_channel.id
     *
     * @return the value of p_channel.id
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_channel.id
     *
     * @param id the value for p_channel.id
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_channel.name
     *
     * @return the value of p_channel.name
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_channel.name
     *
     * @param name the value for p_channel.name
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_channel.type
     *
     * @return the value of p_channel.type
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_channel.type
     *
     * @param type the value for p_channel.type
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_channel.ind
     *
     * @return the value of p_channel.ind
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    public Integer getInd() {
        return ind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_channel.ind
     *
     * @param ind the value for p_channel.ind
     *
     * @mbggenerated Thu Jan 02 09:58:31 CST 2014
     */
    public void setInd(Integer ind) {
        this.ind = ind;
    }
}