package com.flt.dao.model;

public class Consume {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.id
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.name
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.account
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.password
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.thumbnail_path
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private String thumbnailPath;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.id
	 * @return  the value of consumer.id
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.id
	 * @param id  the value for consumer.id
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.name
	 * @return  the value of consumer.name
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.name
	 * @param name  the value for consumer.name
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.account
	 * @return  the value of consumer.account
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.account
	 * @param account  the value for consumer.account
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.password
	 * @return  the value of consumer.password
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.password
	 * @param password  the value for consumer.password
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.thumbnail_path
	 * @return  the value of consumer.thumbnail_path
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public String getThumbnailPath() {
		return thumbnailPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.thumbnail_path
	 * @param thumbnailPath  the value for consumer.thumbnail_path
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setThumbnailPath(String thumbnailPath) {
		this.thumbnailPath = thumbnailPath;
	}
}