package com.flt.dao.model;

public class Consumer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.id
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.name
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.account
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.password
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.thumbnail_path
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	private String thumbnailPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.phone_num
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	private String phoneNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.address
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.email
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consumer.user_id
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.id
	 * @return  the value of consumer.id
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.id
	 * @param id  the value for consumer.id
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.name
	 * @return  the value of consumer.name
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.name
	 * @param name  the value for consumer.name
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.account
	 * @return  the value of consumer.account
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.account
	 * @param account  the value for consumer.account
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.password
	 * @return  the value of consumer.password
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.password
	 * @param password  the value for consumer.password
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.thumbnail_path
	 * @return  the value of consumer.thumbnail_path
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public String getThumbnailPath() {
		return thumbnailPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.thumbnail_path
	 * @param thumbnailPath  the value for consumer.thumbnail_path
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public void setThumbnailPath(String thumbnailPath) {
		this.thumbnailPath = thumbnailPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.phone_num
	 * @return  the value of consumer.phone_num
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public String getPhoneNum() {
		return phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.phone_num
	 * @param phoneNum  the value for consumer.phone_num
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.address
	 * @return  the value of consumer.address
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.address
	 * @param address  the value for consumer.address
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.email
	 * @return  the value of consumer.email
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.email
	 * @param email  the value for consumer.email
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consumer.user_id
	 * @return  the value of consumer.user_id
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consumer.user_id
	 * @param userId  the value for consumer.user_id
	 * @mbggenerated  Mon Feb 03 16:44:14 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}