package com.flt.dao.model;

public class Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_example.id
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_example.id
     *
     * @return the value of tb_example.id
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_example.id
     *
     * @param id the value for tb_example.id
     *
     * @mbggenerated Sat Dec 05 10:41:54 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }
}