package com.flt.dao.model;

import java.util.Date;

public class Order {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.count
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private Integer count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.run_status
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private Integer runStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.tour_name
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private String tourName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.tour_email
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private String tourEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.tour_phone
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private String tourPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.tour_address
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private String tourAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.remark
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.u_dt
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private Date uDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.c_dt
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private Date cDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.consumer_id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private Integer consumerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.article_id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private Integer articleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_order.user_id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.id
	 * @return  the value of t_order.id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.id
	 * @param id  the value for t_order.id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.count
	 * @return  the value of t_order.count
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.count
	 * @param count  the value for t_order.count
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setCount(Integer count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.run_status
	 * @return  the value of t_order.run_status
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public Integer getRunStatus() {
		return runStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.run_status
	 * @param runStatus  the value for t_order.run_status
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setRunStatus(Integer runStatus) {
		this.runStatus = runStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.tour_name
	 * @return  the value of t_order.tour_name
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public String getTourName() {
		return tourName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.tour_name
	 * @param tourName  the value for t_order.tour_name
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setTourName(String tourName) {
		this.tourName = tourName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.tour_email
	 * @return  the value of t_order.tour_email
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public String getTourEmail() {
		return tourEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.tour_email
	 * @param tourEmail  the value for t_order.tour_email
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setTourEmail(String tourEmail) {
		this.tourEmail = tourEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.tour_phone
	 * @return  the value of t_order.tour_phone
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public String getTourPhone() {
		return tourPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.tour_phone
	 * @param tourPhone  the value for t_order.tour_phone
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setTourPhone(String tourPhone) {
		this.tourPhone = tourPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.tour_address
	 * @return  the value of t_order.tour_address
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public String getTourAddress() {
		return tourAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.tour_address
	 * @param tourAddress  the value for t_order.tour_address
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setTourAddress(String tourAddress) {
		this.tourAddress = tourAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.remark
	 * @return  the value of t_order.remark
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.remark
	 * @param remark  the value for t_order.remark
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.u_dt
	 * @return  the value of t_order.u_dt
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public Date getuDt() {
		return uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.u_dt
	 * @param uDt  the value for t_order.u_dt
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setuDt(Date uDt) {
		this.uDt = uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.c_dt
	 * @return  the value of t_order.c_dt
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public Date getcDt() {
		return cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.c_dt
	 * @param cDt  the value for t_order.c_dt
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setcDt(Date cDt) {
		this.cDt = cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.consumer_id
	 * @return  the value of t_order.consumer_id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public Integer getConsumerId() {
		return consumerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.consumer_id
	 * @param consumerId  the value for t_order.consumer_id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setConsumerId(Integer consumerId) {
		this.consumerId = consumerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.article_id
	 * @return  the value of t_order.article_id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public Integer getArticleId() {
		return articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.article_id
	 * @param articleId  the value for t_order.article_id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_order.user_id
	 * @return  the value of t_order.user_id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_order.user_id
	 * @param userId  the value for t_order.user_id
	 * @mbggenerated  Wed Mar 12 14:01:27 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}