package com.flt.dao.model;

public class Passage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_passage.id_passage
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	private Integer id_passage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_passage.passage_title
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	private String passageTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_passage.passage_content
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	private String passageContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_passage.type
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_passage.id_passage
	 * @return  the value of p_passage.id_passage
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	public Integer getId_passage() {
		return id_passage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_passage.id_passage
	 * @param id_passage  the value for p_passage.id_passage
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	public void setId_passage(Integer id_passage) {
		this.id_passage = id_passage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_passage.passage_title
	 * @return  the value of p_passage.passage_title
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	public String getPassageTitle() {
		return passageTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_passage.passage_title
	 * @param passageTitle  the value for p_passage.passage_title
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	public void setPassageTitle(String passageTitle) {
		this.passageTitle = passageTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_passage.passage_content
	 * @return  the value of p_passage.passage_content
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	public String getPassageContent() {
		return passageContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_passage.passage_content
	 * @param passageContent  the value for p_passage.passage_content
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	public void setPassageContent(String passageContent) {
		this.passageContent = passageContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_passage.type
	 * @return  the value of p_passage.type
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_passage.type
	 * @param type  the value for p_passage.type
	 * @mbggenerated  Tue Dec 31 17:59:45 CST 2013
	 */
	public void setType(Integer type) {
		this.type = type;
	}
}