package com.flt.dao.model;

public class PMenu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_menu.menu_id
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	private Integer menu_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_menu.menu_name
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	private String menuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_menu.p_menu_id
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	private Integer pMenuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column p_menu.ind
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	private Integer ind;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_menu.menu_id
	 * @return  the value of p_menu.menu_id
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public Integer getMenu_id() {
		return menu_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_menu.menu_id
	 * @param menu_id  the value for p_menu.menu_id
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public void setMenu_id(Integer menu_id) {
		this.menu_id = menu_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_menu.menu_name
	 * @return  the value of p_menu.menu_name
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_menu.menu_name
	 * @param menuName  the value for p_menu.menu_name
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_menu.p_menu_id
	 * @return  the value of p_menu.p_menu_id
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public Integer getpMenuId() {
		return pMenuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_menu.p_menu_id
	 * @param pMenuId  the value for p_menu.p_menu_id
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public void setpMenuId(Integer pMenuId) {
		this.pMenuId = pMenuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column p_menu.ind
	 * @return  the value of p_menu.ind
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public Integer getInd() {
		return ind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column p_menu.ind
	 * @param ind  the value for p_menu.ind
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public void setInd(Integer ind) {
		this.ind = ind;
	}
}