package com.flt.dao.model;

import java.util.ArrayList;
import java.util.List;

public class PMenuExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public PMenuExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMenu_idIsNull() {
			addCriterion("menu_id is null");
			return (Criteria) this;
		}

		public Criteria andMenu_idIsNotNull() {
			addCriterion("menu_id is not null");
			return (Criteria) this;
		}

		public Criteria andMenu_idEqualTo(Integer value) {
			addCriterion("menu_id =", value, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenu_idNotEqualTo(Integer value) {
			addCriterion("menu_id <>", value, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenu_idGreaterThan(Integer value) {
			addCriterion("menu_id >", value, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenu_idGreaterThanOrEqualTo(Integer value) {
			addCriterion("menu_id >=", value, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenu_idLessThan(Integer value) {
			addCriterion("menu_id <", value, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenu_idLessThanOrEqualTo(Integer value) {
			addCriterion("menu_id <=", value, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenu_idIn(List<Integer> values) {
			addCriterion("menu_id in", values, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenu_idNotIn(List<Integer> values) {
			addCriterion("menu_id not in", values, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenu_idBetween(Integer value1, Integer value2) {
			addCriterion("menu_id between", value1, value2, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenu_idNotBetween(Integer value1, Integer value2) {
			addCriterion("menu_id not between", value1, value2, "menu_id");
			return (Criteria) this;
		}

		public Criteria andMenuNameIsNull() {
			addCriterion("menu_name is null");
			return (Criteria) this;
		}

		public Criteria andMenuNameIsNotNull() {
			addCriterion("menu_name is not null");
			return (Criteria) this;
		}

		public Criteria andMenuNameEqualTo(String value) {
			addCriterion("menu_name =", value, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameNotEqualTo(String value) {
			addCriterion("menu_name <>", value, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameGreaterThan(String value) {
			addCriterion("menu_name >", value, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
			addCriterion("menu_name >=", value, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameLessThan(String value) {
			addCriterion("menu_name <", value, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameLessThanOrEqualTo(String value) {
			addCriterion("menu_name <=", value, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameLike(String value) {
			addCriterion("menu_name like", value, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameNotLike(String value) {
			addCriterion("menu_name not like", value, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameIn(List<String> values) {
			addCriterion("menu_name in", values, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameNotIn(List<String> values) {
			addCriterion("menu_name not in", values, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameBetween(String value1, String value2) {
			addCriterion("menu_name between", value1, value2, "menuName");
			return (Criteria) this;
		}

		public Criteria andMenuNameNotBetween(String value1, String value2) {
			addCriterion("menu_name not between", value1, value2, "menuName");
			return (Criteria) this;
		}

		public Criteria andPMenuIdIsNull() {
			addCriterion("p_menu_id is null");
			return (Criteria) this;
		}

		public Criteria andPMenuIdIsNotNull() {
			addCriterion("p_menu_id is not null");
			return (Criteria) this;
		}

		public Criteria andPMenuIdEqualTo(Integer value) {
			addCriterion("p_menu_id =", value, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andPMenuIdNotEqualTo(Integer value) {
			addCriterion("p_menu_id <>", value, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andPMenuIdGreaterThan(Integer value) {
			addCriterion("p_menu_id >", value, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andPMenuIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("p_menu_id >=", value, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andPMenuIdLessThan(Integer value) {
			addCriterion("p_menu_id <", value, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andPMenuIdLessThanOrEqualTo(Integer value) {
			addCriterion("p_menu_id <=", value, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andPMenuIdIn(List<Integer> values) {
			addCriterion("p_menu_id in", values, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andPMenuIdNotIn(List<Integer> values) {
			addCriterion("p_menu_id not in", values, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andPMenuIdBetween(Integer value1, Integer value2) {
			addCriterion("p_menu_id between", value1, value2, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andPMenuIdNotBetween(Integer value1, Integer value2) {
			addCriterion("p_menu_id not between", value1, value2, "pMenuId");
			return (Criteria) this;
		}

		public Criteria andIndIsNull() {
			addCriterion("ind is null");
			return (Criteria) this;
		}

		public Criteria andIndIsNotNull() {
			addCriterion("ind is not null");
			return (Criteria) this;
		}

		public Criteria andIndEqualTo(Integer value) {
			addCriterion("ind =", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndNotEqualTo(Integer value) {
			addCriterion("ind <>", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndGreaterThan(Integer value) {
			addCriterion("ind >", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndGreaterThanOrEqualTo(Integer value) {
			addCriterion("ind >=", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndLessThan(Integer value) {
			addCriterion("ind <", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndLessThanOrEqualTo(Integer value) {
			addCriterion("ind <=", value, "ind");
			return (Criteria) this;
		}

		public Criteria andIndIn(List<Integer> values) {
			addCriterion("ind in", values, "ind");
			return (Criteria) this;
		}

		public Criteria andIndNotIn(List<Integer> values) {
			addCriterion("ind not in", values, "ind");
			return (Criteria) this;
		}

		public Criteria andIndBetween(Integer value1, Integer value2) {
			addCriterion("ind between", value1, value2, "ind");
			return (Criteria) this;
		}

		public Criteria andIndNotBetween(Integer value1, Integer value2) {
			addCriterion("ind not between", value1, value2, "ind");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table p_menu
	 * @mbggenerated  Tue Dec 31 16:52:23 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table p_menu
     *
     * @mbggenerated do_not_delete_during_merge Tue Dec 31 16:50:48 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}