package com.flt.dao.model;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.id
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.name
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.category_id
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.menu_id
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_product.channel_type
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    private Integer channelType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product.id
     *
     * @return the value of p_product.id
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product.id
     *
     * @param id the value for p_product.id
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product.name
     *
     * @return the value of p_product.name
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product.name
     *
     * @param name the value for p_product.name
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product.category_id
     *
     * @return the value of p_product.category_id
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product.category_id
     *
     * @param categoryId the value for p_product.category_id
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product.menu_id
     *
     * @return the value of p_product.menu_id
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product.menu_id
     *
     * @param menuId the value for p_product.menu_id
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_product.channel_type
     *
     * @return the value of p_product.channel_type
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public Integer getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_product.channel_type
     *
     * @param channelType the value for p_product.channel_type
     *
     * @mbggenerated Thu Jan 02 10:35:12 CST 2014
     */
    public void setChannelType(Integer channelType) {
        this.channelType = channelType;
    }
}