package com.flt.dao.model;

import java.util.Date;

public class Resource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.id
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.text
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private String text;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.idx
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private Integer idx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.num
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.u_dt
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private Date uDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.c_dt
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private Date cDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.user_id
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	private Integer userId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.id
	 * @return  the value of resource.id
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.id
	 * @param id  the value for resource.id
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.text
	 * @return  the value of resource.text
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.text
	 * @param text  the value for resource.text
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setText(String text) {
		this.text = text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.idx
	 * @return  the value of resource.idx
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public Integer getIdx() {
		return idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.idx
	 * @param idx  the value for resource.idx
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.num
	 * @return  the value of resource.num
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.num
	 * @param num  the value for resource.num
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.u_dt
	 * @return  the value of resource.u_dt
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public Date getuDt() {
		return uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.u_dt
	 * @param uDt  the value for resource.u_dt
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setuDt(Date uDt) {
		this.uDt = uDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.c_dt
	 * @return  the value of resource.c_dt
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public Date getcDt() {
		return cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.c_dt
	 * @param cDt  the value for resource.c_dt
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setcDt(Date cDt) {
		this.cDt = cDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.user_id
	 * @return  the value of resource.user_id
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.user_id
	 * @param userId  the value for resource.user_id
	 * @mbggenerated  Sat Jan 25 13:05:47 CST 2014
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}