package com.flt.dao.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.account
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.site_name
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String siteName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.logo_path
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String logoPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.domain
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String domain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.qq_num
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private Long qqNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone_num
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private Long phoneNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.home_address
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String homeAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email_address
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String emailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.site_address
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String siteAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.basic_info
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String basicInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.service_info
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	private String serviceInfo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.account
	 * @return  the value of user.account
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.account
	 * @param account  the value for user.account
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.site_name
	 * @return  the value of user.site_name
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getSiteName() {
		return siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.site_name
	 * @param siteName  the value for user.site_name
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setSiteName(String siteName) {
		this.siteName = siteName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.logo_path
	 * @return  the value of user.logo_path
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getLogoPath() {
		return logoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.logo_path
	 * @param logoPath  the value for user.logo_path
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setLogoPath(String logoPath) {
		this.logoPath = logoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.domain
	 * @return  the value of user.domain
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getDomain() {
		return domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.domain
	 * @param domain  the value for user.domain
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setDomain(String domain) {
		this.domain = domain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.qq_num
	 * @return  the value of user.qq_num
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public Long getQqNum() {
		return qqNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.qq_num
	 * @param qqNum  the value for user.qq_num
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setQqNum(Long qqNum) {
		this.qqNum = qqNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone_num
	 * @return  the value of user.phone_num
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public Long getPhoneNum() {
		return phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone_num
	 * @param phoneNum  the value for user.phone_num
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setPhoneNum(Long phoneNum) {
		this.phoneNum = phoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.home_address
	 * @return  the value of user.home_address
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getHomeAddress() {
		return homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.home_address
	 * @param homeAddress  the value for user.home_address
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email_address
	 * @return  the value of user.email_address
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getEmailAddress() {
		return emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email_address
	 * @param emailAddress  the value for user.email_address
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.site_address
	 * @return  the value of user.site_address
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getSiteAddress() {
		return siteAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.site_address
	 * @param siteAddress  the value for user.site_address
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setSiteAddress(String siteAddress) {
		this.siteAddress = siteAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.basic_info
	 * @return  the value of user.basic_info
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getBasicInfo() {
		return basicInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.basic_info
	 * @param basicInfo  the value for user.basic_info
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setBasicInfo(String basicInfo) {
		this.basicInfo = basicInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.service_info
	 * @return  the value of user.service_info
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public String getServiceInfo() {
		return serviceInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.service_info
	 * @param serviceInfo  the value for user.service_info
	 * @mbggenerated  Tue Mar 11 15:13:30 CST 2014
	 */
	public void setServiceInfo(String serviceInfo) {
		this.serviceInfo = serviceInfo;
	}
}